server:
  port: 0
  address: 0.0.0.0
  servlet:
    context-path: /
spring:
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:mysql://k7c103.p.ssafy.io:3306/doghoogam?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: c103
      password: "!c103finalproject"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

