
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/git/privateStudy/MSA(Spring Cloud/MSA/git-local-repo