server:
  address: 0.0.0.0
  servlet:
    contextPath: /
  port: 8000
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: q1a2z3
    key-store-type: PKCS12
    key-alias: tomcat
    protocol: TLS
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://dog-hoogam.site:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true

      routes:
      - id: user-service
        uri: https://dog-hoogam.site:2000
        predicates:
          - Path=/api/user-service/**
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/api/user-service/(?<path>.*),/$\{path}

      - id: business-service
        uri: lb://BUSINESS-SERVICE
        predicates:
          - Path=/business-service/actuator/**
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/api/business-service/(?<path>.*),/$\{path}

#      - id: business-service
#        uri: lb://BUSINESS-SERVICE
#        predicates:
#          - Path=/api/business-service/swagger-ui/**,/business-service/swagger-resources/**,/business-service/swagger-ui.html,/business-service/v2/api-docs,/business-service/webjars/**,/business-service/view/**
#        filters:
#          - RewritePath=/business-service/(?<path>.*),/$\{path}

      - id: business-service
        uri: lb://BUSINESS-SERVICE
        predicates:
          - Path=/api/business-service/**
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/api/business-service/(?<path>.*),/$\{path}
          - AuthorizationHeaderFilter








#jwt:
#  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
#  expiration: 1296000000
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace

